apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: pre-prod
        name: app-1
        files: values.yaml
      - namespace: prod
        name: app-2
        files: values.prod.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      source:
        helm:
          valueFiles:
          - '{{files}}'
        repoURL: https://github.com/IdanHenik/Gitops-Helm.git
        targetRevision: HEAD
        path: parent
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
        
