
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: pre-prod
        name: app-apache-1
        subchart: apache
        files: values.pre-prod.yaml
      - namespace: prod
        name: app-nginx-2
        subchart: nginx
        files: values.prod.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      source:
        helm:
          chart: parent
          valueFiles:
          - '{{files}}'
          #- charts/{{subchart}}/values.yaml
          releaseName: '{{subchart}}'
          dependencyNames:
          - '{{subchart}}'
        repoURL: https://github.com/IdanHenik/Gitops-Helm.git
        targetRevision: spsific-subchart
        path: parent
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
        
